from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol, runtime_checkable

from keysigil.models.budget import UsageRecord


@runtime_checkable
class StorageBackend(Protocol):
    async def setup(self) -> None: ...
    async def store_key(self, key_data: dict[str, Any]) -> None: ...
    async def get_key_by_hash(self, key_hash: str) -> dict[str, Any] | None: ...
    async def get_key_by_id(self, key_id: str) -> dict[str, Any] | None: ...
    async def list_keys(self, prefix: str | None = None, limit: int = 100) -> list[dict[str, Any]]: ...
    async def revoke_key(self, key_id: str, revoked_at: datetime) -> None: ...
    async def update_key(self, key_id: str, updates: dict[str, Any]) -> None: ...
    async def record_usage(self, record: UsageRecord) -> None: ...
    async def get_usage_stats(self, key_id: str, as_of: datetime) -> dict[str, int]: ...
    async def get_usage_by_model(self, key_id: str) -> dict[str, int]: ...
    async def get_counter(self, key: str) -> int: ...
    async def increment_counter(self, key: str, ttl_seconds: int) -> int: ...
